- workflow-templates/decapod-yaml/sync-yaml-from-git-wftpl.yaml
- workflow-templates/helm-operator/helmrelease-wftpl.yaml
- New WorkflowTemplate named `sync-yaml-from-git`. 
- It's able to  
1. sync HelmRelease manifests built in `decapod-yaml` from git
2. create and update configmaps for each HelmRelease manifests in Kubernetes cluster.
> feature: implement new WorkflowTemplate to sync helmrelease manifests

- workflow-templates/helm-operator/helmrelease-rbac.yaml
- workflow-templates/helm-operator/helmrelease-wftpl.yaml
- create target namespaces if targetNamespace of HelmRelease not exists
> create target namespaces for HelmRelease

- workflow-templates/decapod-yaml/prepare-manifest-wftpl.yaml
* clarify workflow template's name
> refactor: rename sync-manifest-from-git to prepare-manifest

- workflow-templates/helm-operator/helmrelease-wftpl.yaml
* fix bugs to create HelmRelease in `argo` namespace.
> fix: create helmrelease in default namespace

- templates/decapod-yaml/prepare-manifest-wftpl.yaml
잘못된 변수 $i를 $SITE_NAME으로 변경하였습니다.
> bugfix: fix wrong variable $i to $SITE_NAME

- workflows/service-mesh-wf.yaml
> Add new workflow for service mesh

- workflows/lma-federation-wf.yaml
federation lma workflow 에 thanos 를 추가
> Add thanos chart

- templates/argo-additional-rbac.yaml
- templates/helm-operator/cleanup-hr-wftpl.yaml
* helmrelease 를 모두 지우는 cleanup wftpl
* argo default service account에 helmrelease 관련 권한을 주기 위한 rbac
> add cleanup wftpl and additional rbac

- workflows/lma-federation-wf.yaml
- workflows/lma-wf.yaml
* thanos-config는 prometheus 설치 전에 설치되어야 함.
> install thanos-config

- templates/decapod-yaml/prepare-manifest-wftpl.yaml
* decapod-site-yaml이 아닌 decapod-site를 사용하도록 변경
> Refactor to use decapod-site insteads of decapod-site-yaml

- templates/argo-servicemesh-rbac.yaml
- templates/delete-servicemesh-wftpl.yaml
servicemesh 를 revision 으로 삭제하는 workflow 입니다.
template 으로 바로 workflow 를 생성할 수 있게 template 만 추가함
1. kubectl 로 iop 삭제
2. kubernetes resource 삭제
3. 설치 방법인 helm_chart 혹은 istioctl 에 따라 istio operator 를 삭제
- helm chart 방식은 아직 적용이 안되어 있음
- istioctl 로 operator 를 생성했을 경우만 적용됨
> delete servicemesh workflow

- templates/argo-cd/createapp-wftpl.yaml
- templates/argo-cd/prepare-argocd-wftpl.yaml
* container command 줄바꿈에 문제가 있어서 >를 |로 수정후에 잘 되는것 확인
* imagePullPolicy를 IfNotPresent로 변경 (docker hub pull-rate-limit 걸림)
> fix newline problem and imagePullPolicy

- templates/decapod-apps/lma-federation-wftpl.yaml
* lma namespace로 통일하게 되어 fed를 lma로 변경
> removed fed namespace

- workflows/lma-federation-wf.yaml
> lma-federation-wf: fix array syntax

- templates/decapod-apps/lma-federation-wftpl.yaml
* related to PR https://github.com/openinfradev/decapod-base-yaml/pull/84#pullrequestreview-684805632
* addons 안으로 fed-addons가 병합됨
> removed fed-addons

- templates/argo-cd/createapp-wftpl.yaml
* ArgoCD automated sync enabled
> enabled automated sync

- templates/argo-cd/createapp-wftpl.yaml
> added missing environment REVISION

- templates/argo-additional-rbac.yaml
argo v3 테스트 중 부족한 권한이 발견되어 권한 추가함.
> add secret resource to argo rbac

- templates/decapod-apps/remove-servicemesh-all-wftpl.yaml
servicemesh components 를 깨끗이 지우는 argo workflowtemplate.
> Uninstall all servicemesh components

- templates/issue-access-token-wftpl.yaml
* argo API 통신을 위한 access token 발급 workflow template
> added new workflowTemplate to issue access token

- templates/argo-additional-rbac.yaml
argo workflow server 에 namespace 를 delete 할 수 있는 role 을 추가함
> Add delete namespace role into argo-server

- templates/argo-cd/createapp-wftpl.yaml
@seungkyua 님이 지적했던 내용으로 ArgoCD app 레이블을 '클러스터 이름/아이디'-AppGroup 형식으로 변경하는 내용입니다.
> createapp: fix argcd app label

- templates/argo-additional-rbac.yaml
- templates/argo-cd/prepare-argocd-wftpl.yaml
- argocd에 'sealed-secrets' project 생성
- argo가 사용하는 rbac에 'sealed-secrets' CR 관련 권한 추가
> create sealed-secrets project

- scripts/use_private_registry.sh
decapod-flow 내 워크플로우 템플릿에서 사용하는 컨테이너 이미지 주소를 내부 저장소로 변경하는 스크립트입니다.
> add script for using private registry

- .github/workflows/lint.yml
`decapod-flow`의 WorkflowTemplate의 대한 Lint Test 입니다.
Pull Request 시 변경 파일에 대해 Lint Test를 수행합니다.
테스트 PR: Jaesang/argo-workflow#1
성공케이스: https://github.com/Jaesang/argo-workflow/runs/4891214027?check_suite_focus=true
실패케이스:  https://github.com/Jaesang/argo-workflow/runs/4891208545?check_suite_focus=true
> Add lint test for WorkflowTemplate

- templates/argo-cd/createapp-wftpl.yaml
- templates/argo-cd/delete-apps-by-label-wftpl.yaml
- templates/argo-cd/prepare-argocd-wftpl.yaml
- templates/decapod-apps/remove-servicemesh-all-wftpl.yaml
- templates/decapod-apps/service-mesh-wf.yaml
https://github.com/openinfradev/tks-issues/issues/148
'Replace' 옵션 사용 위해 CLI 버전 업데이트 필요
> use new argocd-cli image

- templates/argo-additional-rbac.yaml
- templates/argo-cd/delete-apps-by-label-wftpl.yaml
- templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
https://github.com/openinfradev/tks-issues/issues/97
lma 삭제시 지워지지 않고 남아있는 자원들 삭제하는 부분 추가했습니다.
> add step to remove leftover resources in lma

- templates/argo-additional-rbac.yaml
remove-usercluster WF 수행시 필요한 권한 추가
> add 'clusters' to argo rbac

- templates/decapod-apps/install-admin-tools-wftpl.yaml
> admin-tools: fix keycloak install configuration

- templates/argo-cd/prepare-argocd-wftpl.yaml
BYOH 프로바이더 등 다른 cluster api 인프라 프로바이더 추가를 위해 공통 부분(tks-cluster-common)과 프로바이더 전용 부분 (tks-cluster-aws/byoh) 으로 분리하였습니다.
> support multi cluster api infra providers

- templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
@seungkyua 님 PR 과 동일한 내용입니다.
https://github.com/openinfradev/decapod-flow/pull/94
> feature. change cluster id

- templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
- templates/decapod-apps/service-mesh-wf.yaml
> rollback. "[WIP] reduce cluster_id length"

- templates/decapod-apps/lma-uniformed-wftpl.yaml
- templates/decapod-apps/service-mesh-wf.yaml
fluentbit-operator를 fluent-operator로 명칭일 바뀌면서 decapod flow에 변경되어야 하는 사항을 반영
다음 세가지 pr이 동시에 merge 되어야 함
- https://github.com/openinfradev/decapod-site/pull/95
- https://github.com/openinfradev/decapod-base-yaml/pull/170
- https://github.com/openinfradev/decapod-flow/pull/98
> fluent의 공식 오퍼레이터를 사용하면서 변경된 내역을 반영

- templates/decapod-apps/lma-uniformed-wftpl.yaml
minio를 따로 설치하도록 구성했습니다.
decapod-base-yaml와 세트로 변경되어야 합니다.
테스트를 위해 강제 merge하겠습니다.
> minio: dedicated installation for shared service(thanos/loki)

- templates/argo-cd/prepare-argocd-wftpl.yaml
- templates/decapod-apps/install-admin-tools-wftpl.yaml
- templates/decapod-apps/lma-uniformed-wftpl.yaml
- templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
- templates/decapod-apps/remove-servicemesh-all-wftpl.yaml
- templates/decapod-apps/service-mesh-wf.yaml
워크플로우 이미지 정의에서 불필요한 따옴표 문자 사용을 제거합니다.
> remove unnecessary quote characters from image definitions

- templates/decapod-apps/install-admin-tools-wftpl.yaml
- templates/decapod-apps/lma-uniformed-wftpl.yaml
- templates/decapod-apps/remove-servicemesh-all-wftpl.yaml
change image url
harbor 에는 변경된 이미지를 업로드 하였음
> change original images url to harbor image url

- templates/argo-cd/create-app-wftpl.yaml
- templates/argo-cd/delete-apps-wftpl.yaml
- templates/argo-cd/prepare-argocd-wftpl.yaml
- templates/decapod-apps/install-admin-tools-wftpl.yaml
- templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
- templates/decapod-apps/service-mesh-wf.yaml
- templates/issue-access-token-wftpl.yaml
> fix missing image url

- templates/decapod-apps/service-mesh-wf.yaml
유선 통화했던 elastic-system namespace 추가건입니다.
> bugfix. add namespace 'elastic-system' to servicemesh workflow

- templates/decapod-apps/lma-uniformed-wftpl.yaml
organization을 갖고 있는 경우 lma 워크플로우에서 통합(federation)을 위한 인프라를 설치하지 않는다.
> PrimaryCluster: do not install logging infras on a member cluster

- templates/argo-cd/delete-apps-wftpl.yaml
- templates/decapod-apps/lma-uniformed-wftpl.yaml
- ETCD 가 외부에 노출되지 않으므로 메트릭 접근을 위한 인증서 시크릿 생성 부분을 EKS일때에는 실행하지 않도록 했습니다.
- argocd app 삭제 할 때 현재 진행 중인 작업(sync 등)이 있을 경우 무한 대기하는 문제가 있어 이를 중단하는 내용을 추가하였는데 terminate-op 명령어가 하나의 앱만을 받을 수 있어 이를 수정하였습니다.
> LMA: EKS 지원을 위한 수정

- templates/argo-cd/create-app-wftpl.yaml
- templates/argo-cd/delete-apps-wftpl.yaml
- templates/argo-cd/prepare-argocd-wftpl.yaml
- templates/decapod-apps/install-admin-tools-wftpl.yaml
- templates/decapod-apps/lma-uniformed-wftpl.yaml
- templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
- templates/decapod-apps/remove-servicemesh-all-es-wftpl.yaml
- templates/decapod-apps/remove-servicemesh-all-wftpl.yaml
- templates/decapod-apps/service-mesh-es-wf.yaml
- templates/decapod-apps/service-mesh-wf.yaml
- templates/issue-access-token-wftpl.yaml
- https://github.com/openinfradev/decapod-site/pull/168
- https://github.com/openinfradev/decapod-base-yaml/pull/259
- https://github.com/openinfradev/decapod-flow/pull/124
- https://github.com/openinfradev/tks-flow/pull/245
- https://github.com/openinfradev/helm-charts/pull/197
> change image repo from harbor-cicd to harbor

- templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
- templates/decapod-apps/remove-servicemesh-all-es-wftpl.yaml
- templates/decapod-apps/remove-servicemesh-all-wftpl.yaml
- templates/decapod-apps/service-mesh-es-wf.yaml
- templates/decapod-apps/service-mesh-wf.yaml
{{ClusterID}}-kubeconfig 를 {{ClusterID}}-tks-kubeconfig 로 변경
> change kubeconfig to tks-kubeconfig

- templates/decapod-apps/lma-uniformed-wftpl.yaml
opa관련 모니터링을 위한 exporter 초기버전 추가
- https://github.com/openinfradev/decapod-base-yaml/pull/311
- https://github.com/openinfradev/decapod-flow/pull/141
> opa-exporter: add exporter for opa

- templates/decapod-apps/lma-uniformed-wftpl.yaml
아래내역은 세트임
- https://github.com/openinfradev/helm-charts/pull/240
- https://github.com/openinfradev/tks-flow/pull/377
- https://github.com/openinfradev/decapod-site/pull/242
- https://github.com/openinfradev/decapod-base-yaml/pull/323
- https://github.com/openinfradev/decapod-flow/pull/144
> User logging 지원 

- templates/decapod-apps/lma-uniformed-wftpl.yaml
> 20241002 release from develop
