openinfradev/decapod-flow

workflow-templates/helm-operator/helmrelease-rbac.yaml
* argo-deploy-sa serviceaccount needs to create, list namespaces resource in k8s cluster.
=> fix: add create, list authority for argo-deploy-sa

workflow-templates/helm-operator/helmrelease-rbac.yaml
* use `argo` namespace instead `default` namespace
=> fix: use 'argo' namespace by default

templates/decapod-yaml/prepare-manifest-wftpl.yaml, workflows/lma-federation-wf.yaml, workflows/lma-wf.yaml
https://github.com/openinfradev/decapod-base-yaml/issues/23
* elasticsearch-operator 대신 eck-operator와 eck-resource를 사용하여 elasticsearch, kibana 를 띄운다.
* prepare-manifest의 base-yaml-tag parameter를 추가한다. eck-operator를 사용하기 이전의 base-yaml을 사용해야할 수도 있기 때문이다.
=> replace elasticsearch-opeprator to  eck-operator/eck-resource.

templates/decapod-yaml/prepare-manifest-wftpl.yaml
* password를 항상 encode하지 않아도 된다. urlencode를 사용하지 않고 git clone을 하도록 수정.
=> remove urlencode in prepare-manifest wftpl

workflows/service-mesh-wf.yaml
https://github.com/openinfradev/decapod-base-yaml/pull/46 에서 controlplane과 gateway를 별도의 helm release로 분리하였으므로, workflow에도 반영이 되어야함.
default로 (gating 용도로) controlplane과 gateway를 모두 배포하되, 실제 사이트 구축 시에는 site별 workflow를 사용하여 gateway를 제외하고 배포 가능함.
=> update service-mesh-wf to deploy both istio controlplane and gateway HR

templates/argo-cd/createapp-wftpl.yaml, templates/argo-cd/prepare-argocd-wftpl.yaml, workflows/v2/lma-federation-wf.yaml, workflows/v2/lma-wf.yaml, workflows/v2/openstack-components-wf.yaml, workflows/v2/openstack-infra-wf.yaml, workflows/v2/service-mesh-wf.yaml
* repository_url은 가변적인 파라미터 이므로 prepare_argocd 설정에서 빼고 application 생성 시점에 설정하도록 변경한다.
=> add repository_url parameter into application workflow

templates/argo-cd/createapp-wftpl.yaml, templates/argo-cd/prepare-argocd-wftpl.yaml
* prepare-argocd workflow에서 argocd 의 project를 생성
* application을 생성할 때, project parameter를 입력한다.
=> create argocd projects and register applications with projects

templates/argo-cd/createapp-wftpl.yaml, templates/argo-cd/prepare-argocd-wftpl.yaml, templates/decapod-apps/lma-federation-wftpl.yaml, templates/decapod-apps/lma-wftpl.yaml, templates/decapod-apps/openstack-components-wf.yaml, templates/decapod-apps/openstack-infra-wftpl.yaml, templates/decapod-apps/service-mesh-wf.yaml
- prepare-argocd, createapp workflow template 에 argo namespace 를 추가
- prepare-argocd 에서 argo proj 가 존재하면 skip 하고 없을 때만 생성하는 로직 추가
- git branch 를 arguments에  추가하여 decapod-manifest 의 branch 를 선택하여 배포할 수 있는 로직 추가
=> Add argo namespace to workflowtemplate

templates/decapod-yaml/prepare-manifest-wftpl.yaml
taco에서 사용하는 기본 스토리지클래스 이름이 `taco-storage`로 변경되어, 관련 변수를 수정합니다.
=> Change storageclass to 'taco-storage'

templates/decapod-apps/tks-lma-federation-wftpl.yaml
lma-federation-wf에 tks에 연동하여 endpoint를 등록하는 post process추가
입력하는 방법은 다음 3가지
1. eplist 변수에 json 형태로 어플리케이션별 모든 url 제공 "{\"1\":\"127.0.0.1\",\"2\":\"127.0.0.1:10232\"}"
2. clusterep에 클러스터에 대한 ip혹은 dns를 명시하고 epportlist변수에 어플리케이션별 포트를 제공 "{\"1\":\"30000\",\"2\":\"30005\"}"
3. clusterep에 클러스터에 대한 ip 혹은 dns를 적용하여 미리 정해진 내용을 등록하도록 유도 - 현재는 30007 포트만 prometheus sidecar 서비스로 등재
=> add post-process feature for tks

templates/argo-cd/createapp-wftpl.yaml, templates/decapod-apps/service-mesh-wf.yaml
- helm-chart 가 먼저 적용되어야 함.
관련 PR: [openinfradev/helm-charts/pull/48]
- decapod-base-yaml 이 먼저 적용되어야 함
관련 PR: [openinfradev/decapod-base-yaml/pull/88]
- decapod-site 가 먼저 적용되어야 함
관련 PR: [openinfradev/decapod-site/pull/39]
- istio-system ns 는 servicemesh-controlplane 차트에서는 생성하지 않고 workflow 에서 생성함 (argocd app 으로 삭제하면 istio-system ns 가 같이 삭제되기 때문)
- 설치 마지막에 argocd app sync -l app=service-mesh 로 모든 앱에 sync 를 호출함
- Missing 이나 OutOfSync 로 변하는 app 이 존재하여 sync 를 호출하면 해결됨
- create-application workflowtemplate 에서 app 생성시에 app=service-mesh 라벨을 추가함
- 아래 label 을 노드에 추가해야 함 (추후 tacoplay 에 추가 예정)
> 1. servicemesh control node
>     servicemesh=enabled
> 
> 2. servicemesh ingress node
>     taco-ingress-gateway=enabled
> 
> 3. servicemesh egress node
>     taco-egress-gateway=enabled
- Ingress 와 resources …
=> servicemesh refactoring

templates/decapod-apps/tks-lma-federation-wftpl.yaml
* workflow template 이름이 중복이어서 변경
* missing input parameter 문제 수정
=> fix: renamed duplicate workflow template name

templates/argo-cd/createapp-wftpl.yaml, templates/argo-cd/prepare-argocd-wftpl.yaml, templates/decapod-apps/remove-servicemesh-all-wftpl.yaml, templates/decapod-apps/service-mesh-wf.yaml
* plaintext option이 없으면 WARNING prompt로 TLS 없이 설정되었다고 접속하겠냐고 물어봄
=> fix: added plaintext option to argocd cli

templates/decapod-apps/lma-uniformed-wftpl.yaml
LMA workflow에 prepare-etcd-secret helm chart를 추가하였습니다.
이 helm chart는 etcd secret을 만들고, 이 secret은 prometheus 실행을 위해 필수적으로 필요합니다.
관련 PR: https://github.com/openinfradev/decapod-site/pull/57
=> Add prepare-etcd-secret for lma

templates/decapod-apps/lma-uniformed-wftpl.yaml
because 'lma' namespace must exist before deploy 'lma' apps.
=> Create 'lma' namespace before deploy 'lma' apps.

templates/argo-cd/createapp-wftpl.yaml
Argocd 에 App을 생성할 때 타겟 클러스터 이름의 앞 8자리가 Prefix로 추가되어 App 이름으로 사용되도록 수정하였습니다.
=> createapp: add cluster prefix to app names

templates/argo-cd/createapp-wftpl.yaml, templates/decapod-apps/lma-uniformed-wftpl.yaml, templates/decapod-manifests/update-decapod-manifest-wftpl.yaml
https://github.com/openinfradev/tks-issues/issues/55 관련 내용을 반영한 PR 입니다.
어디서든 공통의 create-application workflow를 사용하게 하였고, 다양한 케이스에 대처하기 위해 몇가지 parameter를 추가하였습니다.
자세한 내용은 위의 이슈 내용 참고하시면 됩니다.
한가지 의견을 구하고 싶은 점은, app_prefix 인자를 추가하였는데, 둘 중 어느 쪽이 나은지 의견 부탁드립니다.  (현재는 1번 안으로 되어있음)
1. 기본적으로는 argocd app 생성시 prefix 없이 app name을 사용하고, app_prefix를 입력한 경우에만 붙이도록 한다. (single cluster만 사용하는 경우도 있으므로)
2. app_prefix 의 default 값을 'site_name'으로 지정하고, 사용자가 app_prefix를 명시적으로 입력한 경우에는 해당 prefix를 사용하게 한다  (https://github.com/openinfradev/decapod-flow/pull/63/files#diff-35d3da8a5cd700ba3b07ba314ec4a26708c0f4e5a1e8f1e6852e5c0344f74624R23 주석을 풀어야 함)
=> Refactor createapp

templates/decapod-apps/lma-uniformed-wftpl.yaml
efk 와 loki 중 선택하여 배포할 수 있도록 lma workflow를 수정하였습니다. 
https://github.com/openinfradev/tks-issues/issues/42
현재 파이프라인이 일단 우리가 가진 모든 차트를 decapod-manifests로 렌더링해놓고,  그중에 뭘 배포할지 workflow에서 최종 선택하는 방식이라 kustomize를 활용한 layering이 아니라 본 방식으로 구현하게 되었습니다.
=> make logging_component selectable

templates/argo-cd/createapp-wftpl.yaml, templates/decapod-apps/lma-uniformed-wftpl.yaml
app_prefix 가 개별 template level의 input param으로 되어있다보니, tks-flow/lma -> decapod-flow/lma -> create-app 과 같은 순서로 호출되는 경우, decapod-flow 쪽이 아닌 tks-flow 쪽에서 이 param을 override할 수 있는 방법이 없더군요.   그래서 workflow param으로 변경하여, tks-flow 쪽에서 override할 수 있게 수정하였습니다.
=> move app_prefix to workflow param

templates/decapod-apps/lma-uniformed-wftpl.yaml
다음 두가지 내용 퀵하게 fix해서 올립니다
- Loki 설치 시 eventrouter 함께 배포
- LMA 설치 시 target_cluster parameter 지정 (bug fix)
=> LMA workflow 수정

templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
=> remove-lma-uniformed: fix wrong template name

templates/argo-cd/createapp-wftpl.yaml, templates/decapod-apps/lma-uniformed-wftpl.yaml
https://github.com/openinfradev/tks-issues/issues/137
- Crd를 배포하는 ArgoCD App 에 한해 'Replace' option 적용하도록 create-app WF 수정
- lma workflow 에 추가로 crd-only app도 배포하도록 추가
(주의) https://github.com/openinfradev/decapod-base-yaml/pull/147 과 동시에 merge되어야 합니다.
참고로, servicemesh workflow 는 https://github.com/openinfradev/decapod-flow/pull/70 이 최종 merge되어야 본 PR 로직대로 수정 가능할 것 같습니다
=> set 'replace' sync-option for crd-only app

templates/argo-additional-rbac.yaml, templates/argo-cd/delete-apps-by-label-wftpl.yaml, templates/decapod-apps/lma-uniformed-wftpl.yaml, templates/decapod-apps/remove-lma-uniformed-wftpl.yaml
아래 버그 픽스하는 PR 입니다.
https://github.com/openinfradev/tks-issues/issues/182
관련된 https://github.com/openinfradev/tks-flow/pull/41 도 함께 리뷰 부탁드립니다
=> remove prometheus CR before LMA appgroup removal

templates/argo-cd/delete-apps-by-label-wftpl.yaml
Argo CD appgroup 삭제시, 요청한 label이 존재하지 않는 경우 실패 처리하도록 수정. 
Otherwise, 몇몇 Workflow에서 다음 스텝으로 진행되어버려서 문제가 되네요.
=> make it fail when app filter doesn't match

templates/decapod-apps/remove-servicemesh-all-wftpl.yaml, templates/decapod-apps/service-mesh-wf.yaml
Service-Mesh 설치를 공통 createApp template 을 사용하게 하여 tks 재사용 가능하게 refactoring 했음.
=> Refactoring Service-Mesh workflow for tks and decapod

templates/argo-cd/create-app-wftpl.yaml, templates/decapod-apps/remove-servicemesh-all-wftpl.yaml, templates/decapod-apps/service-mesh-wf.yaml
Change istio operator to istio helm charts
Upgrade charts
- istio-1.13.1
- jaeger-operator-2.27.1 (app: v1.29.1)
- kiali-operator-1.45.1 (app: v1.45.1)
- istio-grafana-dashboard-1.13.1
=> upgrade istio 1.13.1

templates/argo-cd/prepare-argocd-wftpl.yaml, templates/decapod-apps/install-admin-tools-wftpl.yaml, templates/decapod-apps/remove-admin-tools-wftpl.yaml
keycloak 설치를 위한 워크플로우 템플릿을 추가합니다.
=> Admin-tools 워크플로우템플릿 추가: keycloak 설치

templates/argo-cd/delete-apps-wftpl.yaml
- handle cases such as 'istiod-crds' which doesn't have word 'operator' in argoCD app name
=> fix: delete CRDs after normal resources

templates/argo-cd/delete-apps-wftpl.yaml
app 삭제시 상태 체크를 위해 exact matching을 사용하도록 수정합니다. 
금일 cluster-autoscaler 와 cluster-autoscaler-rbac 을 구분 못하는 버그가 발견되었기에 픽스합니다. 
(실제 WF를 돌려보진 못하고, 대신 grep 명령 테스트를 통해 정확한 키워드만 검출하는 것을 확인했습니다)
=> bugfix: check app status using exact matching

templates/argo-additional-rbac.yaml
Argo 네임스페이스의 default sa를 추가 권한 중 Secret에 대한 Patch 내용을 추가합니다.
참고: https://github.com/openinfradev/decapod-flow/blob/d82d97c835596e3c4d1e58b7f28d22abfe5734a3/templates/argo-cd/prepare-argocd-wftpl.yaml#L38
=> add secret patch role for argo

templates/argo-cd/delete-apps-wftpl.yaml, templates/decapod-apps/remove-servicemesh-all-wftpl.yaml, templates/decapod-apps/service-mesh-wf.yaml
move eck and kibana to servicemesh
fix delete-apps when using grep
=> move eck and kibana installation to servicemesh and fix to delete-apps

templates/decapod-apps/remove-lma-uniformed-wftpl.yaml, templates/decapod-apps/remove-servicemesh-all-wftpl.yaml
LMA & service-mesh 삭제시 우선 autosync를 모두 끄고, fluentbit CR 을 먼저 삭제하도록 수정합니다. 
(CR보다 service-account 등이 먼저 삭제되어 삭제시 hang 걸리는 이슈를 해결)
=> disable auto-sync & add CR deletion

templates/decapod-apps/remove-admin-tools-wftpl.yaml
RFC1123 규약에 맞지 않는 스텝 이름을 수정합니다.
=> remove-admins-tools: fix wrong step name

.github/workflows/lint.yml
1. `argo template lint` 명령으로 워크플로우템플릿 검증 시 local에 있는 워크플로우템플릿 파일에 경우에도 쿠버네티스 컨피그를 요구함(아래 3과 같은 이유로 추측)
2. 액션 인스턴스에서 접근할 수 있는 쿠버네티스 클러스터가 마땅치 않아 fake kubeconfig를 사용함
3. 워크플로우템플릿이 내부에서 다른 워크플로우템플릿을 호출하는 경우 이 워크플로우템플릿을 쿠버네티스 클러스터에서 찾는데 
4. 이 때마다 fake kubeconfig에 있는 서버로 접근하려 하고 connection refused에러 발생 (https://github.com/openinfradev/decapod-flow/runs/5766950526?check_suite_focus=true)
- CI용 클러스터가 구축됨에 따라(https://github.com/openinfradev/tks-issues/issues/88 ) fake kubeconfig를 CI용 클러스터의 kubeconfig로 교체 
-  kubeconfig에 명시된 user `test`는 존재하지 않는 유저로 쿠버네티스에서 'system:anonymous'권한으로 실행됨
-  `argo template lint`에서 필요한 get workflowtemplate만 수행할 수 있도록 cicd 클러스터에 롤바인딩 적용하여 다른 보안 위협 제거
=> Add kubeconfig for linting workflow template

templates/decapod-apps/service-mesh-wf.yaml
user cluster 에 접근하기 위해서 user cluster 의 kubeconfig 를 받아오는 부분이 있는데, admin 에서 관리하는 user cluster 의 namespace 가 cluster id 8자리로 줄어들면서 namespace 를 못찾는 문제가 발생했다.
cluster id 를 substr 으로 8자리로 자르는 로직을 추가했음.
e2e 테스트가 성공하는 것을 확인하고 merge 해야 함.
=> [WIP] reduce cluster_id length

templates/argo-cd/prepare-argocd-wftpl.yaml
kustomize의  다수의 리소스를 합치는 기능을 활용하여 다양한 변형을 지원할수 있다.
tks-cluster를 만드는 부분에서 infra를 함께 선택하여 aws나 byoh에 적용가능하다. (kustomization.yaml 작성시 포함한다. 다음은 aws 예시)
```
$  cat cluster/kustomization.yaml
resources:
- ../base
- ../infra/aws
transformers:
- site-values.yaml
```
다음 두 pr이 동시 merge되어야 함
- https://github.com/openinfradev/decapod-site/pull/92
- https://github.com/openinfradev/decapod-base-yaml/pull/167
- https://github.com/openinfradev/tks-flow/pull/105
- https://github.com/openinfradev/decapod-flow/pull/96
=> using structured kustomize document on infra-selection

templates/decapod-apps/service-mesh-wf.yaml
- add jaeger image url
- add istio-ingress-gateway image url
=> add jaeger image and istio-ingress-gateway image url

templates/argo-cd/create-app-wftpl.yaml
ArgoCD 대상 Git 저장소 주소 정보를 secret (git-svc-token)을 통해 얻어 사용하도록 수정하였습니다.
=> Git 저장소 접근 정보를 Secret을 통해 얻습니다

templates/decapod-apps/lma-uniformed-wftpl.yaml
thanos를 기본으로 설치하지 않음 (single cluster의 경우)
멀티클러스터 연동은 primary cluster를 통해 활용됨
=> primary cluster 체계를 위한 기본값 변경

templates/decapod-apps/lma-uniformed-wftpl.yaml
의존성 지정 과정에서 발생한 오타(lma-operators 에서 s 누락)를 수정합니다.
=> lma: fix typo error

templates/decapod-apps/lma-uniformed-wftpl.yaml
LMA 구축시 process-exporter 설치를 제외합니다.
=> deploy-lma: remove process-exporter from lma deployment

templates/argo-cd/create-app-wftpl.yaml, templates/argo-cd/prepare-argocd-wftpl.yaml
Argo CD가 자동으로 NS를 생성하게 sync-option 추가합니다.
=> auto-create namespace

templates/argo-cd/create-app-wftpl.yaml, templates/argo-cd/prepare-argocd-wftpl.yaml, templates/decapod-apps/lma-uniformed-wftpl.yaml
- https://github.com/openinfradev/tks-flow/pull/256
- https://github.com/openinfradev/decapod-flow/pull/130
- https://github.com/openinfradev/decapod-base-yaml/pull/265
- https://github.com/openinfradev/decapod-site/pull/178
- https://github.com/openinfradev/helm-charts/pull/216
=> policy: add a decapod app for policies
